/**
 * \author Daniel Keefe (dfk)
 *
 * \file  VRG3D.H
 *
 */


#ifndef VRG3D_H
#define VRG3D_H

// Include all of G3D
#include <G3D/G3DAll.h>

// Include all of the VRG3D library here
#include "ConfigMap.H"
#include "DisplayTile.H"
#include "Event.H"
#include "EventNet.H"
#include "G3DOperators.H"
#include "InputDevice.H"
#include "MouseToTracker.H"
#include "ProjectionVRCamera.H"
#include "SynchedSystem.H"
#include "VRApp.H"
#include "VRPNAnalogDevice.H"
#include "VRPNButtonDevice.H"
#include "VRPNTrackerDevice.H"

//using namespace VRG3D;

#include <iostream>
using namespace std;

#include "PlatformDefs.h"


#endif
